#!/bin/sh
echo "Running pre-commit checks ..."

# Run the checks
./gradlew spotlessCheck detekt checkModuleVersions

# Get the exit code of the last command
RESULT=$?

if [ $RESULT -ne 0 ]; then
  echo "-----------------------------------"
  echo "Pre-commit checks FAILED."
  echo "Run './gradlew spotlessApply detekt' to fix formatting and detekt issues."
  echo "-----------------------------------"
  exit 1
fi

echo "Checks passed! Committing..."
exit 0