#!/bin/sh
echo "Running pre-push checks ..."

# Run the checks
./gradlew checkModuleVersions

# Get the exit code of the last command
RESULT=$?

if [ $RESULT -ne 0 ]; then
  echo "-----------------------------------"
  echo "Pre-commit checks FAILED."
  echo "Run './gradlew updateModuleVersions' to fix versions."
  echo "-----------------------------------"
  exit 1
fi

echo "Checks passed! Committing..."
exit 0