#open -a 'google chrome' ./stats/build/dokka/html/index.html

./gradlew :docs:dokkaGenerate
#HTML pages generated by Dokka need to be hosted on a web server in order to render everything (incl. side menu) correctly.
open 'http://localhost:63342/CRYPTO-SDK/docs/build/dokka/html/index.html'
